name: billbuddy
description: Aplikasi manajemen tagihan dan pengingat pembayaran
publish_to: 'none' # this prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Layanan - Versi yang kompatibel
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9

  # UI & Utility
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

# Gunakan versi yang kompatibel untuk web
dependency_overrides:
  firebase_auth_web: ^5.8.12
  firebase_messaging_web: ^3.5.18
  js: ^0.6.7