// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_9o3uCcwC9ZDtji7UTKD200sULngsLHI',
    appId: '1:1041211637118:web:83780b00fc5bb68ce0872f',
    messagingSenderId: '1041211637118',
    projectId: 'billbuddy-33ff6',
    authDomain: 'billbuddy-33ff6.firebaseapp.com',
    storageBucket: 'billbuddy-33ff6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2mFmx-jx-sUySrWbb6LMoTscFvakDqk',
    appId: '1:1041211637118:android:0f9b45f2e7491a63e0872f',
    messagingSenderId: '1041211637118',
    projectId: 'billbuddy-33ff6',
    storageBucket: 'billbuddy-33ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRf3ORLLl_TVaCOzPszebHiPnk-W4Su4',
    appId: '1:1041211637118:ios:9e5714ac4dd3432ce0872f',
    messagingSenderId: '1041211637118',
    projectId: 'billbuddy-33ff6',
    storageBucket: 'billbuddy-33ff6.firebasestorage.app',
    iosBundleId: 'com.example.anggaop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRf3ORLLl_TVaCOzPszebHiPnk-W4Su4',
    appId: '1:1041211637118:ios:9e5714ac4dd3432ce0872f',
    messagingSenderId: '1041211637118',
    projectId: 'billbuddy-33ff6',
    storageBucket: 'billbuddy-33ff6.firebasestorage.app',
    iosBundleId: 'com.example.anggaop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_9o3uCcwC9ZDtji7UTKD200sULngsLHI',
    appId: '1:1041211637118:web:5a17ebbf2147674ce0872f',
    messagingSenderId: '1041211637118',
    projectId: 'billbuddy-33ff6',
    authDomain: 'billbuddy-33ff6.firebaseapp.com',
    storageBucket: 'billbuddy-33ff6.firebasestorage.app',
  );
}
